
version: '3.8'
services:
  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    networks:
      - comp

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pedro123
      MYSQL_DATABASE: dados_comp
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"  
    networks:
      - comp

volumes: 
  db_data:
  nodered_data:

networks:
  comp: 
    driver: bridge
