version: '3.8'
services:
  node-red:
    build: ./Node-red
    ports:
      - "9095:1880"
    volumes:
      - nodered_data:/data

    networks:
      - compressor

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: compressor
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"  
    networks:
      - compressor
  
  data-service:
    build: ./dataService
    ports: 
      - "5010:5000"
    networks:
      - compressor
    depends_on:
      - node-red

volumes: 
  db_data:
  nodered_data:

networks:
  compressor: 
    driver: bridge
