// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb04Ql5_qFqTRozs9TtGWmZbQT9W5x4K8',
    appId: '1:1018148994227:web:b8991caee281a8ad1c04c6',
    messagingSenderId: '1018148994227',
    projectId: 'jhmobile-58f96',
    authDomain: 'jhmobile-58f96.firebaseapp.com',
    storageBucket: 'jhmobile-58f96.firebasestorage.app',
    measurementId: 'G-G0Y6F8HCGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv1MTWxM_74IYvgqPiQxi5B3aXkLBMvMc',
    appId: '1:1018148994227:android:851a2e0a87f8a3e81c04c6',
    messagingSenderId: '1018148994227',
    projectId: 'jhmobile-58f96',
    storageBucket: 'jhmobile-58f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOLX6XFdmmh_MNYkTXt5oiHmEljsIPL8',
    appId: '1:1018148994227:ios:32990ab120e522d41c04c6',
    messagingSenderId: '1018148994227',
    projectId: 'jhmobile-58f96',
    storageBucket: 'jhmobile-58f96.firebasestorage.app',
    iosBundleId: 'com.example.jhMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOLX6XFdmmh_MNYkTXt5oiHmEljsIPL8',
    appId: '1:1018148994227:ios:32990ab120e522d41c04c6',
    messagingSenderId: '1018148994227',
    projectId: 'jhmobile-58f96',
    storageBucket: 'jhmobile-58f96.firebasestorage.app',
    iosBundleId: 'com.example.jhMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb04Ql5_qFqTRozs9TtGWmZbQT9W5x4K8',
    appId: '1:1018148994227:web:92ab0a9d19c5af2c1c04c6',
    messagingSenderId: '1018148994227',
    projectId: 'jhmobile-58f96',
    authDomain: 'jhmobile-58f96.firebaseapp.com',
    storageBucket: 'jhmobile-58f96.firebasestorage.app',
    measurementId: 'G-9251V9J7MT',
  );
}
