name: jh_mobile
description: Compressor SENAI.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  salomon_bottom_bar: ^3.3.1
  convex_bottom_bar: ^3.0.0
  syncfusion_flutter_gauges: ^29.2.5
  sqflite: ^2.0.3
  get_it: ^8.0.3
  path_provider: ^2.0.11
  fl_chart: ^0.65.0
  another_flushbar: ^1.10.29
  mqtt_client: ^10.8.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.2.6
  connectivity_plus: ^4.0.0
  network_info_plus: ^4.0.0
  device_info_plus: ^10.1.0
  google_nav_bar: ^5.0.7
  animations: ^2.0.7
  line_icons: ^2.0.1
  persistent_bottom_nav_bar_v2: ^5.4.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/compresor.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/compresor.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/compresor.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/compresor.png"

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

